import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { getLoggedInUser } from "@/lib/actions/auth.action";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const loggedUser = await getLoggedInUser()

    return (
        <html lang="en">
            <body
                className={`${inter.className} antialiased`}
            >
                <Header loggedUser={loggedUser}/>
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}
